apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: QuotaPolicy
metadata:
  name: deepseek-r1-distill-llama-8b-quota
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: aigateway.envoyproxy.io
    kind: AIServiceBackend
    name: deepseek-r1-distill-llama-8b
  serviceQuota:
    quota:
      limit: 500
      duration: 1m
